import os
import time
import requests

GITHUB_API="https://api.github.com"

def _headers()->dict:
    token=os.environ["GITHUB_TOKEN"]
    return{
        "Authorization":f"Bearer {token}",
        "Accept":"application/vnd.github+json",
    }

def _repo_slug()->str:
    return os.environ["GITHUB_REPOSITORY"]

def create_or_update_pr(base_branch:str, head_branch:str)->dict:
    url=f"{GITHUB_API}/repos/{_repo_slug()}/pulls"

    existing=requests.get(
        url,headers=_headers(),
        params={"head":f"{_repo_slug().split('/')[0]}:{head_branch}","base":base_branch}
    )
    existing.raise_for_status()
    open_prs=existing.json()

    if open_prs:
        return open_prs[0]
    
    response=requests.post(url, headers=_headers(), json={
        "title":"docs: update README, API docs, and architecture diagram",
        "head":head_branch,
        "base":base_branch,
        "body":"Auto-generated by AutoDocs based on the latest push. Review and merge to update your project's documentation.",
    })
    response.raise_for_status()
    return response.json()

def _get_pr_mergeable_state(pr_number:int,max_wait_seconds:int=15)->bool:
    url=f"{GITHUB_API}/repos/{_repo_slug()}/pulls/{pr_number}"
    waited=0

    while waited<max_wait_seconds:
        response=requests.get(url,headers=_headers())
        response.raise_for_status()
        data=response.json()
        if data["mergeable"] is not None:
            return bool(data["mergeable"])
        time.sleep(3)
        waited+=3
    return False

def merge_pr_if_clean(pr_number:int)->str:
    is_mergeable=_get_pr_mergeable_state(pr_number)
    if not is_mergeable:
        return "conflict"
    url=f"{GITHUB_API}/repos/{_repo_slug()}/pulls/{pr_number}/merge"
    response=requests.put(url, headers=_headers(), json={
        "merge_method":"squash",
    })
    if response.status_code==200:
        return "merged"
    
    return "left_open"



